baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Termunicions'
[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"
[markup.goldmark.renderer]
  unsafe = true

