baseURL = 'sakaloner.github.com/blog'
languageCode = 'en-us'
title = "Andres' Blog"
[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"
[markup.goldmark.renderer]
  unsafe = true

